### ISSUE TITLE
Tooltip Color Value + WallPaper

### ISSUE THREAD

**Issue by peter-power-594** [Vimux/icewm-theme-icepick#1]
Heya @Vimux,

Thank you for the share. Your theme is working great. Even with a recent machine, in case you are short in memory and if you  prefer the X environment instead of Wayland, IceWM is really really nice :+1: I'm currently using it as my daily box with my laptop.

Two quick feedbacks :

1) Inside the file IcePick/default.theme, the  value for the ColorToolTip is missing a "0"
"#00000" => "#000000" You need six digits to my mind ;-)  
(I found a log message in my .xsession-errors home folder)

2) I don't know about the licenses, I would appreciate if you could share the original wallpaper as seen as on your screenshot. It's something related to Firefox or Lofi Music or something like that ?

Kind Regards

**Comment by Vimux** [comment]
Hi.

> "#00000" => "#000000" You need six digits to my mind ;-)

Yes, good catch. Do you want to do a PR or should I make the changes myself?

> I would appreciate if you could share the original wallpaper as seen as on your screenshot. It's something related to Firefox or Lofi Music or something like that ?

I don't know the original source, but there is an article on Medium.com "Context Graph: It’s time to bring context back to the web" with identical image cover. Additionally, if you search for images on any popular search engine using the keywords "minimalism forest fox art" or "forest mozilla firefox art", you will find the same wallpaper image.

> Thank you for the share. Your theme is working great. 

Glad to hear that. However, given that IceWM development is ongoing, it's likely that there are new features that the theme doesn't support or that look inconsistent.

**Comment by peter-power-594** [comment]
Hi @Vimux :-)

Thank you very much for the feedbacks, you rock :1st_place_medal: 

- Feel free to make the change on your side please, I didn't plan to open a PR for a tiny digit :1234: 
- I found the wallpaper, greatly appreciate your tip for the search :+1: 
- Eheh yes, and even if your theme is not fully filled with features, it's a perfect start :+1: 

Here is my current setup :
![ksnip_20240601-231115](https://github.com/Vimux/icewm-theme-icepick/assets/70574048/2b3b3738-3831-499b-8deb-5de4937d4193)

I found valuable information while googling and from the following article :
https://github.com/KF-Art/icewm-personal-tunning

There are interesting distros like AntiX, Mint, etc... to run with a bit old hardware but I stick with Fedora for my workstation mainly for web development purposes. I saved lots of memory and resources with IceWM and the good old X Window Environment, especially on my laptop. I appreciate your personal touch with IcePick as it's playing nicely with the Nord or Dracula color scheme. :100: 

Thanks again, and best for the future

**Comment by Vimux** [comment]
> Feel free to make the change on your side please, I didn't plan to open a PR for a tiny digit 🔢

Fixed. 4eb4ec8797bb4169253adc550d3fa0e3aa6fc922

> Eheh yes, and even if your theme is not fully filled with features, it's a perfect start 👍
> I appreciate your personal touch with IcePick as it's playing nicely with the Nord or Dracula color scheme. 💯

Thank you for the kind words. My best wishes to you for the success of your project.

Closed.
